require('dotenv').config();
const path=require('path'),crypto=require('crypto'),http=require('http'),express=require('express'),mongoose=require('mongoose'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),multer=require('multer');
const {Server}=require('socket.io');const {S3Client,PutObjectCommand}=require('@aws-sdk/client-s3');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=+process.env.PORT||3000,JWT=process.env.JWT_SECRET||crypto.randomBytes(48).toString('hex');
app.set('trust proxy',1);app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
const O=mongoose.Schema.Types.ObjectId;
const User=mongoose.model('User',new mongoose.Schema({name:{type:String,required:true},username:{type:String,required:true,unique:true,lowercase:true,match:/^[a-z0-9_]{3,32}$/},email:{type:String,default:'',lowercase:true},password:{type:String,required:true},avatar:{type:String,default:''},bio:{type:String,default:''},role:{type:String,default:'user'},lastSeen:{type:Date,default:Date.now}},{timestamps:true}));
const Chat=mongoose.model('Chat',new mongoose.Schema({type:{type:String,enum:['dm','group','channel'],required:true},title:{type:String,default:''},username:{type:String,unique:true,sparse:true,lowercase:true},description:{type:String,default:''},owner:{type:O,ref:'User',required:true},members:[{user:{type:O,ref:'User'},role:{type:String,default:'member'}}],dmKey:{type:String,unique:true,sparse:true},public:{type:Boolean,default:false},lastMessage:{type:O,ref:'Msg'}},{timestamps:true}));
const Msg=mongoose.model('Msg',new mongoose.Schema({chat:{type:O,ref:'Chat',index:true},sender:{type:O,ref:'User'},text:{type:String,default:''},file:{url:String,name:String,mime:String,size:Number},reactions:[{emoji:String,users:[{type:O,ref:'User'}]}]},{timestamps:true}));
const Bot=mongoose.model('Bot',new mongoose.Schema({owner:{type:O,ref:'User'},name:String,username:{type:String,unique:true,lowercase:true},tokenHash:String,tokenPrefix:String,webhook:{type:String,default:''},enabled:{type:Boolean,default:true}},{timestamps:true}));
const clean=u=>u?{id:String(u._id),name:u.name,username:u.username,email:u.email,avatar:u.avatar,bio:u.bio,role:u.role,lastSeen:u.lastSeen}:null;
const member=(c,id)=>c.members.some(m=>String(m.user?._id||m.user)===String(id));
const sign=u=>jwt.sign({id:String(u._id)},JWT,{expiresIn:'30d'});
async function auth(req,res,next){try{const h=req.headers.authorization||'',p=jwt.verify(h.replace(/^Bearer /,''),JWT),u=await User.findById(p.id);if(!u)throw 0;req.user=u;next()}catch{res.status(401).json({error:'Unauthorized'})}}
const R2=process.env.R2_ACCOUNT_ID&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY&&process.env.R2_BUCKET&&process.env.R2_PUBLIC_BASE_URL;
const s3=R2?new S3Client({region:'auto',endpoint:`https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,credentials:{accessKeyId:process.env.R2_ACCESS_KEY_ID,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY}}):null,up=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});
function view(c,uid){const x=c.toObject?c.toObject():c;let title=x.title,avatar='';if(x.type==='dm'){const o=x.members.map(m=>m.user).find(u=>String(u?._id||u)!==String(uid));title=o?.name||o?.username||'Chat';avatar=o?.avatar||''}return{id:String(x._id),type:x.type,title,username:x.username||'',description:x.description||'',public:!!x.public,avatar,members:x.members.map(m=>({user:clean(m.user),role:m.role})),memberCount:x.members.length,lastMessage:x.lastMessage||null,updatedAt:x.updatedAt}}
const sm=m=>{const x=m.toObject?m.toObject():m;return{id:String(x._id),chat:String(x.chat),sender:clean(x.sender),text:x.text,file:x.file||null,reactions:x.reactions||[],createdAt:x.createdAt}};
app.get('/api/health',(_,r)=>r.json({ok:true,service:'Lumo',mongo:mongoose.connection.readyState===1,r2:!!R2}));
app.post('/api/register',async(req,res)=>{try{let{name,username,email,password}=req.body;username=String(username||'').toLowerCase().trim();if(String(name||'').trim().length<2||!/^[a-z0-9_]{3,32}$/.test(username)||String(password||'').length<6)return res.status(400).json({error:'Ma’lumotlarni tekshiring'});if(await User.exists({username}))return res.status(409).json({error:'Username band'});const u=await User.create({name:String(name).trim(),username,email:String(email||'').toLowerCase().trim(),password:await bcrypt.hash(password,10)});res.json({token:sign(u),user:clean(u)})}catch(e){res.status(500).json({error:'Register xatosi'})}});
app.post('/api/login',async(req,res)=>{const q=String(req.body.login||'').toLowerCase().trim(),u=await User.findOne({$or:[{username:q},{email:q}]});if(!u||!await bcrypt.compare(String(req.body.password||''),u.password))return res.status(401).json({error:'Login yoki parol xato'});res.json({token:sign(u),user:clean(u)})});
app.get('/api/me',auth,(req,res)=>res.json({user:clean(req.user)}));
app.patch('/api/me',auth,async(req,res)=>{['name','bio','avatar'].forEach(k=>{if(req.body[k]!==undefined)req.user[k]=String(req.body[k]).trim()});await req.user.save();res.json({user:clean(req.user)})});
app.get('/api/users',auth,async(req,res)=>{const q=String(req.query.q||'').trim(),rx=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const a=q?await User.find({_id:{$ne:req.user._id},$or:[{name:rx},{username:rx}]}).limit(20):[];res.json({users:a.map(clean)})});
app.get('/api/chats',auth,async(req,res)=>{const a=await Chat.find({'members.user':req.user._id}).sort({updatedAt:-1}).populate('members.user','name username avatar bio role lastSeen').populate({path:'lastMessage',populate:{path:'sender',select:'name username avatar'}});res.json({chats:a.map(x=>view(x,req.user._id))})});
app.post('/api/dm',auth,async(req,res)=>{const id=String(req.body.userId||'');if(!mongoose.isValidObjectId(id)||id===String(req.user._id))return res.status(400).json({error:'User noto‘g‘ri'});const ids=[String(req.user._id),id].sort(),key=ids.join(':');let c=await Chat.findOne({dmKey:key});if(!c)c=await Chat.create({type:'dm',owner:req.user._id,dmKey:key,members:ids.map((user,i)=>({user,role:i?'member':'owner'}))});c=await Chat.findById(c._id).populate('members.user','name username avatar bio role lastSeen');res.json({chat:view(c,req.user._id)})});
app.post('/api/chats',auth,async(req,res)=>{try{const type=req.body.type==='channel'?'channel':'group',title=String(req.body.title||'').trim(),username=String(req.body.username||'').toLowerCase().trim();if(title.length<2)return res.status(400).json({error:'Nom kiriting'});if(username&&!/^[a-z0-9_]{3,32}$/.test(username))return res.status(400).json({error:'Username noto‘g‘ri'});let c=await Chat.create({type,title,username:username||undefined,description:String(req.body.description||''),public:!!req.body.public,owner:req.user._id,members:[{user:req.user._id,role:'owner'}]});c=await Chat.findById(c._id).populate('members.user','name username avatar bio role lastSeen');res.json({chat:view(c,req.user._id)})}catch{res.status(409).json({error:'Username band yoki xato'})}});
app.get('/api/explore',auth,async(req,res)=>{const q=String(req.query.q||'').trim(),f={public:true,type:{$in:['group','channel']}};if(q){const rx=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');f.$or=[{title:rx},{username:rx}]}const a=await Chat.find(f).sort({updatedAt:-1}).limit(50).populate('members.user','name username avatar bio role lastSeen');res.json({chats:a.map(x=>view(x,req.user._id))})});
app.post('/api/chats/:id/join',auth,async(req,res)=>{const c=await Chat.findById(req.params.id);if(!c||!c.public)return res.status(404).json({error:'Topilmadi'});if(!member(c,req.user._id)){c.members.push({user:req.user._id});await c.save()}res.json({ok:true})});
app.get('/api/chats/:id/messages',auth,async(req,res)=>{const c=await Chat.findById(req.params.id);if(!c||!member(c,req.user._id))return res.status(403).json({error:'Ruxsat yo‘q'});const a=await Msg.find({chat:c._id}).sort({createdAt:-1}).limit(80).populate('sender','name username avatar bio role lastSeen');res.json({messages:a.reverse().map(sm)})});
async function send(c,u,b){const m=await Msg.create({chat:c._id,sender:u._id,text:String(b.text||'').trim(),file:b.file||undefined});c.lastMessage=m._id;c.updatedAt=new Date();await c.save();return Msg.findById(m._id).populate('sender','name username avatar bio role lastSeen')}
app.post('/api/chats/:id/messages',auth,async(req,res)=>{const c=await Chat.findById(req.params.id);if(!c||!member(c,req.user._id))return res.status(403).json({error:'Ruxsat yo‘q'});const role=c.members.find(m=>String(m.user)===String(req.user._id))?.role;if(c.type==='channel'&&!['owner','admin'].includes(role))return res.status(403).json({error:'Kanalga faqat admin yozadi'});if(!String(req.body.text||'').trim()&&!req.body.file?.url)return res.status(400).json({error:'Xabar bo‘sh'});const m=await send(c,req.user,req.body),d=sm(m);io.to('c:'+c._id).emit('message',d);res.json({message:d})});
app.post('/api/messages/:id/react',auth,async(req,res)=>{const m=await Msg.findById(req.params.id),e=String(req.body.emoji||'❤️').slice(0,8);if(!m)return res.status(404).json({error:'Topilmadi'});const c=await Chat.findById(m.chat);if(!member(c,req.user._id))return res.status(403).json({error:'Ruxsat yo‘q'});let r=m.reactions.find(x=>x.emoji===e);if(!r)m.reactions.push({emoji:e,users:[req.user._id]});else{const i=r.users.findIndex(x=>String(x)===String(req.user._id));i>=0?r.users.splice(i,1):r.users.push(req.user._id)}await m.save();io.to('c:'+m.chat).emit('reaction',{id:String(m._id),reactions:m.reactions});res.json({reactions:m.reactions})});
app.post('/api/upload',auth,up.single('file'),async(req,res)=>{if(!R2)return res.status(503).json({error:'R2 sozlanmagan'});if(!req.file)return res.status(400).json({error:'Fayl kerak'});const safe=(req.file.originalname||'file').replace(/[^\w.-]/g,'_'),key=`lumo/${Date.now()}-${crypto.randomUUID()}-${safe}`;await s3.send(new PutObjectCommand({Bucket:process.env.R2_BUCKET,Key:key,Body:req.file.buffer,ContentType:req.file.mimetype}));res.json({file:{url:process.env.R2_PUBLIC_BASE_URL.replace(/\/$/,'')+'/'+key,name:req.file.originalname,mime:req.file.mimetype,size:req.file.size}})});
app.get('/api/bots',auth,async(req,res)=>res.json({bots:(await Bot.find({owner:req.user._id}).sort({createdAt:-1})).map(b=>({id:String(b._id),name:b.name,username:b.username,webhook:b.webhook,enabled:b.enabled}))}));
app.post('/api/bots',auth,async(req,res)=>{try{const username=String(req.body.username||'').toLowerCase().trim();if(!/^[a-z0-9_]{3,28}bot$/.test(username))return res.status(400).json({error:'Username bot bilan tugasin'});const token=crypto.randomBytes(8).toString('hex')+':'+crypto.randomBytes(24).toString('base64url'),b=await Bot.create({owner:req.user._id,name:String(req.body.name||'Bot').trim(),username,tokenPrefix:token.split(':')[0],tokenHash:crypto.createHash('sha256').update(token).digest('hex')});res.json({bot:{id:String(b._id),name:b.name,username:b.username,token}})}catch{res.status(409).json({error:'Bot username band'})}});
app.patch('/api/bots/:id',auth,async(req,res)=>{const b=await Bot.findOne({_id:req.params.id,owner:req.user._id});if(!b)return res.status(404).json({error:'Topilmadi'});b.webhook=String(req.body.webhook||'').trim();await b.save();res.json({ok:true})});
async function botFrom(t){if(!t.includes(':'))return null;const a=await Bot.find({tokenPrefix:t.split(':')[0],enabled:true});return a.find(b=>b.tokenHash===crypto.createHash('sha256').update(t).digest('hex'))||null}
app.post('/bot/:token/sendMessage',async(req,res)=>{const b=await botFrom(req.params.token);if(!b)return res.status(401).json({ok:false});const c=await Chat.findById(req.body.chat_id),u=await User.findById(b.owner);if(!c||!u||!member(c,u._id))return res.status(403).json({ok:false,error:'Bot owner chat a’zosi bo‘lishi kerak'});const m=await send(c,u,{text:`🤖 ${b.name}\n${String(req.body.text||'')}`}),d=sm(m);io.to('c:'+c._id).emit('message',d);res.json({ok:true,result:d})});
app.get('/bot/:token/getMe',async(req,res)=>{const b=await botFrom(req.params.token);res.status(b?200:401).json(b?{ok:true,result:{id:String(b._id),name:b.name,username:b.username}}:{ok:false})});
app.post('/bot/:token/setWebhook',async(req,res)=>{const b=await botFrom(req.params.token);if(!b)return res.status(401).json({ok:false});b.webhook=String(req.body.url||'');await b.save();res.json({ok:true})});
io.use(async(s,n)=>{try{const p=jwt.verify(s.handshake.auth?.token||'',JWT),u=await User.findById(p.id);if(!u)throw 0;s.user=u;n()}catch{n(new Error('unauthorized'))}});io.on('connection',s=>{s.on('join',async id=>{const c=mongoose.isValidObjectId(id)&&await Chat.findById(id);if(c&&member(c,s.user._id))s.join('c:'+id)});s.on('typing',async d=>{const c=mongoose.isValidObjectId(d.chatId)&&await Chat.findById(d.chatId);if(c&&member(c,s.user._id))s.to('c:'+d.chatId).emit('typing',{chatId:d.chatId,name:s.user.name,on:!!d.on})})});
app.get('/manifest.json',(_,res)=>res.json({name:'Lumo Messenger',short_name:'Lumo',start_url:'/',display:'standalone',background_color:'#080c17',theme_color:'#6d5dfc'}));
app.get('/sw.js',(_,res)=>res.type('application/javascript').send(`const C='lumo-v1';self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(['/']))));self.addEventListener('fetch',e=>{if(e.request.method==='GET'&&!new URL(e.request.url).pathname.startsWith('/api/'))e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)))})`));
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/lumo').then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('Lumo :'+PORT))).catch(e=>{console.error(e);process.exit(1)});